### ISSUE TITLE
The Game crashed when a Red Tango hit me with Fire

### ISSUE THREAD

**Issue by TaladirX** [Wehavecookies56/Kingdom-Keys#5]
Basically explained in the title so here is the crash report.

---- Minecraft Crash Report ----
// My bad.

Time: 1/18/21 6:10 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at online.kingdomkeys.kingdomkeys.entity.magic.FireEntity.func_70184_a(FireEntity.java:88) ~[?:2.0.1.2] {re:classloading}
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:134) ~[?:?] {re:classloading}
	at online.kingdomkeys.kingdomkeys.entity.magic.FireEntity.func_70071_h_(FireEntity.java:64) ~[?:2.0.1.2] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$5466/335082207.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at online.kingdomkeys.kingdomkeys.entity.magic.FireEntity.func_70184_a(FireEntity.java:88)
	at net.minecraft.entity.projectile.ThrowableEntity.func_70071_h_(ThrowableEntity.java:134)
	at online.kingdomkeys.kingdomkeys.entity.magic.FireEntity.func_70071_h_(FireEntity.java:64)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
	at net.minecraft.world.server.ServerWorld$$Lambda$5466/335082207.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: kingdomkeys:entity_fire (online.kingdomkeys.kingdomkeys.entity.magic.FireEntity)
	Entity ID: 75602
	Entity Name: entity.kingdomkeys.entity_fire
	Entity's Exact location: -8800.60, 72.43, -1819.07
	Entity's Block location: World: (-8801,72,-1820), Chunk: (at 15,4,4 in -551,-114; contains blocks -8816,0,-1824 to -8801,255,-1809), Region: (-18,-4; contains chunks -576,-128 to -545,-97, blocks -9216,0,-2048 to -8705,255,-1537)
	Entity's Momentum: -0.96, -0.02, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['TaladirX'/64701, l='Destiny Island', x=-8801.37, y=71.00, z=-1819.50]]
	Chunk stats: ServerChunkCache: 4349
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Destiny Island
	Level seed: -7054928272839925811
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (256,64,-144), Chunk: (at 0,4,0 in 16,-9; contains blocks 256,0,-144 to 271,255,-129), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 307570 game time, 342132 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 63253 (now: false), thunder time: 22767 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1981453712 bytes (1889 MB) / 2896691200 bytes (2762 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.2+70+master.2845bb9
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-2.2.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.47.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.47.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.47
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.10.0.64-SNAPSHOT.jar Useful Backpacks {usefulbackpacks@1.10.0.64-SNAPSHOT DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		Kingdom+Keys+1.15.2-2.0.1.2.jar Kingdom Keys {kingdomkeys@2.0.1.2 DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['TaladirX'/64701, l='Destiny Island', x=-8801.37, y=71.00, z=-1819.50]]
	Data Packs: mod:oreexcavation (incompatible), vanilla, mod:usefulbackpacks, mod:elevatorid, mod:forge (incompatible), mod:uteamcore, mod:waystones (incompatible), mod:kingdomkeys (incompatible), mod:journeymap (incompatible), mod:ironchest, mod:jei (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Wehavecookies56** [comment]
Fixed in da1d68d243b09ac611ef2f074f28b0ccbb8c06a5
